spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hyron
    username: hyron
    password: hyron
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
server:
  port: 8080
